/**
 * @file    config.c
 * @brief   GENERATED by tools/erosgen.py from TaskRateToggler.yaml - DO NOT EDIT
 *
 * Const configuration tables in PROGMEM; the pool arena is the
 * only RAM contributed here (user payload, reported separately
 * from the kernel RAM budget).
 */

#include <avr/pgmspace.h>

#include "eros.h"

const OsTaskConfigType OS_taskConfig[OS_NUM_TASKS] PROGMEM =
{
    [TASK_INIT] = { Task_Init, 1u /* autostart */, 1u /* WCET ticks */ },
    [TASK_APPTASKRATE_100MS] = { Task_appTaskRate_100ms, 0u /* autostart */, 1u /* WCET ticks */ },
    [TASK_APPTASKRATE_50MS] = { Task_appTaskRate_50ms, 0u /* autostart */, 1u /* WCET ticks */ },
    [TASK_APPTASKRATE_10MS] = { Task_appTaskRate_10ms, 0u /* autostart */, 1u /* WCET ticks */ },
};

const OsAlarmConfigType OS_alarmConfig[OS_NUM_ALARMS] PROGMEM =
{
    [ALARM_APPTASKRATE_10MS] = { TASK_APPTASKRATE_10MS },
    [ALARM_APPTASKRATE_50MS] = { TASK_APPTASKRATE_50MS },
    [ALARM_APPTASKRATE_100MS] = { TASK_APPTASKRATE_100MS },
};

const OsResourceConfigType OS_resourceConfig[OS_NUM_RESOURCES] PROGMEM =
{
    [RES_RESOURCE_1] = { TASK_APPTASKRATE_10MS /* ceiling */, 0u /* mask tick ISR */ },
};

uint8_t OS_poolArena[(uint16_t)OS_POOL_NUM_BLOCKS * OS_POOL_BLOCK_SIZE];
