/**
 * @file    Rte.h
 * @brief   GENERATED by tools/erosgen.py from TaskRateToggler.yaml - DO NOT EDIT
 *
 * RTE public API for the 'appTaskRate_10ms', 'appTaskRate_50ms', 'appTaskRate_100ms' model<->OS integration.
 */

#ifndef RTE_H
#define RTE_H

/** BSW init for the bound ports + ASW init. Call once, with
 *  interrupts disabled (StartupHook via os_gen.h). */
void Rte_Init(void);

/** One activation: read input ports <- BSW, run the runnable,
 *  write output ports -> BSW. */
void Rte_Run_appTaskRate_10ms(void);
void Rte_Run_appTaskRate_50ms(void);
void Rte_Run_appTaskRate_100ms(void);

#endif /* RTE_H */
