/**
 * @file    Rte.c
 * @brief   GENERATED by tools/erosgen.py from TaskRateToggler.yaml - DO NOT EDIT
 *
 * RTE implementation for the 'appTaskRate_10ms', 'appTaskRate_50ms', 'appTaskRate_100ms' model<->OS integration:
 * port adapters (IoHwAb) + lifecycle. Touches the ASW only through
 * its exported interface globals and the BSW through driver APIs.
 */

#include <avr/io.h>

#include "Rte.h"
#include "Rte_Cfg.h"

/* ASW - generated models (read-only) */
#include "appTaskRate.h"
#include "appTaskRate_Intfc.h"

/* OS: the runnable is wrapped as an EROS task (Task_<model>). */
#include "eros.h"
#include "config.h"

/* --- Port adapters (IoHwAb): BSW signals <-> ASW ports ---------- */

static void Rte_Write_appTaskRate_10ms_Toggler_B(uint8_t on)
{
    if (on)
    {
        RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_PORT |= (uint8_t)(1u << RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_BIT);
    }
    else
    {
        RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_PORT &= (uint8_t)~(1u << RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_BIT);
    }
}

static void Rte_Write_appTaskRate_50ms_Toggler_B(uint8_t on)
{
    if (on)
    {
        RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_PORT |= (uint8_t)(1u << RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_BIT);
    }
    else
    {
        RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_PORT &= (uint8_t)~(1u << RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_BIT);
    }
}

static void Rte_Write_appTaskRate_100ms_Toggler_B(uint8_t on)
{
    if (on)
    {
        RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_PORT |= (uint8_t)(1u << RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_BIT);
    }
    else
    {
        RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_PORT &= (uint8_t)~(1u << RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_BIT);
    }
}

/* --- Per-instance state ---------------------------------------- */
/* Instances of one SWC share its single set of exported globals, so */
/* each instance's state is saved here and context-switched around  */
/* its runnable (see the task bodies below). ------------------------ */
static boolean_T rte_appTaskRate_10ms_OUT_Toggler_B;
static boolean_T rte_appTaskRate_50ms_OUT_Toggler_B;
static boolean_T rte_appTaskRate_100ms_OUT_Toggler_B;

/* --- Lifecycle ------------------------------------------------- */

void Rte_Init(void)
{
    /* appTaskRate_10ms */
    /* BSW init for the bound ports. */
    RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_DDR  |= (uint8_t)(1u << RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_BIT);
    RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_PORT &= (uint8_t)~(1u << RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_BIT);

    /* ASW init. */
    RTE_CFG_APPTASKRATE_10MS_INIT_FN();

    /* appTaskRate_50ms */
    /* BSW init for the bound ports. */
    RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_DDR  |= (uint8_t)(1u << RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_BIT);
    RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_PORT &= (uint8_t)~(1u << RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_BIT);

    /* ASW init. */
    RTE_CFG_APPTASKRATE_50MS_INIT_FN();

    /* appTaskRate_100ms */
    /* BSW init for the bound ports. */
    RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_DDR  |= (uint8_t)(1u << RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_BIT);
    RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_PORT &= (uint8_t)~(1u << RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_BIT);

    /* ASW init. */
    RTE_CFG_APPTASKRATE_100MS_INIT_FN();
}

void Rte_Run_appTaskRate_10ms(void)
{
    /* run the ASW runnable */
    RTE_CFG_APPTASKRATE_10MS_RUNNABLE_FN();

    /* implicit write: actuator ports -> BSW */
    Rte_Write_appTaskRate_10ms_Toggler_B(RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_SIGNAL);
}

void Rte_Run_appTaskRate_50ms(void)
{
    /* run the ASW runnable */
    RTE_CFG_APPTASKRATE_50MS_RUNNABLE_FN();

    /* implicit write: actuator ports -> BSW */
    Rte_Write_appTaskRate_50ms_Toggler_B(RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_SIGNAL);
}

void Rte_Run_appTaskRate_100ms(void)
{
    /* run the ASW runnable */
    RTE_CFG_APPTASKRATE_100MS_RUNNABLE_FN();

    /* implicit write: actuator ports -> BSW */
    Rte_Write_appTaskRate_100ms_Toggler_B(RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_SIGNAL);
}

/* --- OS task body: the cyclic alarm (armed by os_gen.h) ---------- */
/* activates this task; it runs one pass and terminates. --------- */

void Task_appTaskRate_10ms(void)
{
    OUT_Toggler_B = rte_appTaskRate_10ms_OUT_Toggler_B;  /* restore instance state */
    Rte_Run_appTaskRate_10ms();
    rte_appTaskRate_10ms_OUT_Toggler_B = OUT_Toggler_B;  /* save instance state */
    TerminateTask();
}

void Task_appTaskRate_50ms(void)
{
    OUT_Toggler_B = rte_appTaskRate_50ms_OUT_Toggler_B;  /* restore instance state */
    Rte_Run_appTaskRate_50ms();
    rte_appTaskRate_50ms_OUT_Toggler_B = OUT_Toggler_B;  /* save instance state */
    TerminateTask();
}

void Task_appTaskRate_100ms(void)
{
    OUT_Toggler_B = rte_appTaskRate_100ms_OUT_Toggler_B;  /* restore instance state */
    Rte_Run_appTaskRate_100ms();
    rte_appTaskRate_100ms_OUT_Toggler_B = OUT_Toggler_B;  /* save instance state */
    TerminateTask();
}
