/**
 * @file    Rte_appTaskRate_50ms.h
 * @brief   GENERATED by tools/erosgen.py from TaskRateToggler.yaml - DO NOT EDIT
 *
 * Contract-phase application header for the 'appTaskRate_50ms' SWC: its RTE
 * run entry + the ports it binds. Include this alone to compile the
 * SWC's integration before the full system Rte.h is configured.
 */

#ifndef RTE_APPTASKRATE_50MS_H
#define RTE_APPTASKRATE_50MS_H

/* Output ports (ASW -> BSW actuator): */
/*   OUT_Toggler_B (boolean_T) -> dio */

/** One activation of this SWC: read inputs -> run -> write outputs. */
void Rte_Run_appTaskRate_50ms(void);

#endif /* RTE_APPTASKRATE_50MS_H */
