/**
 * @file    Rte_Cfg.h
 * @brief   GENERATED by tools/erosgen.py from TaskRateToggler.yaml - DO NOT EDIT
 *
 * Declarative ASW<->BSW binding for 3 SWCs ('appTaskRate_10ms', 'appTaskRate_50ms', 'appTaskRate_100ms'):
 * which driver feeds each input port, which each output port
 * actuates, and each runnable rate. Pure configuration, no logic.
 */

#ifndef RTE_CFG_H
#define RTE_CFG_H

/* ================= SWC: appTaskRate_10ms ================= */
/* ---- SWC identity (ASW entry points) ---------------------------- */
#define RTE_CFG_APPTASKRATE_10MS_INIT_FN appTaskRate_initialize
#define RTE_CFG_APPTASKRATE_10MS_RUNNABLE_FN appKnbSwt_Runnable

/* ---- Output ports: ASW port -> BSW actuator --------------------- */
/* OUT_Toggler_B (boolean_T) -> dio */
#define RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_SIGNAL OUT_Toggler_B
#define RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_DDR DDRD
#define RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_PORT PORTD
#define RTE_CFG_APPTASKRATE_10MS_TOGGLER_B_BIT 1u

/* ---- Scheduling: runnable rate assigned to the OS -------------- */
#define RTE_CFG_APPTASKRATE_10MS_PERIOD_MS 10u

/* ================= SWC: appTaskRate_50ms ================= */
/* ---- SWC identity (ASW entry points) ---------------------------- */
#define RTE_CFG_APPTASKRATE_50MS_INIT_FN appTaskRate_initialize
#define RTE_CFG_APPTASKRATE_50MS_RUNNABLE_FN appKnbSwt_Runnable

/* ---- Output ports: ASW port -> BSW actuator --------------------- */
/* OUT_Toggler_B (boolean_T) -> dio */
#define RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_SIGNAL OUT_Toggler_B
#define RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_DDR DDRD
#define RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_PORT PORTD
#define RTE_CFG_APPTASKRATE_50MS_TOGGLER_B_BIT 2u

/* ---- Scheduling: runnable rate assigned to the OS -------------- */
#define RTE_CFG_APPTASKRATE_50MS_PERIOD_MS 50u

/* ================= SWC: appTaskRate_100ms ================= */
/* ---- SWC identity (ASW entry points) ---------------------------- */
#define RTE_CFG_APPTASKRATE_100MS_INIT_FN appTaskRate_initialize
#define RTE_CFG_APPTASKRATE_100MS_RUNNABLE_FN appKnbSwt_Runnable

/* ---- Output ports: ASW port -> BSW actuator --------------------- */
/* OUT_Toggler_B (boolean_T) -> dio */
#define RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_SIGNAL OUT_Toggler_B
#define RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_DDR DDRD
#define RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_PORT PORTD
#define RTE_CFG_APPTASKRATE_100MS_TOGGLER_B_BIT 3u

/* ---- Scheduling: runnable rate assigned to the OS -------------- */
#define RTE_CFG_APPTASKRATE_100MS_PERIOD_MS 100u

#endif /* RTE_CFG_H */
